# HTTP Server
server:
  port: 8888

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
      #defaultZone: http://localhost:8761/eureka/ //TODO cannot use in profile, since we need native profile for config