# HTTP Server
server:
  port: ${PORT:8888}

# Spring properties
spring:
  application:
    name: config-service
  # otherwise You need to configure a uri for the git repository
  profiles:
      active: native

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/