# HTTP Server
server:
  port: ${PORT:8091}

# Spring properties
spring:
  application:
    name: customer-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/