# HTTP Server
server:
  port: 8091

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Used when config-service is not found
app:
  test:
    value: customer-service__application_yml

---
#Dev Docker profile
spring:
  profiles: dev_docker
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/