# HTTP Server
server:
  port: ${PORT:8092}

# Spring properties
spring:
  application:
    name: order-service
  profiles:
    active: dev
  cloud:
    config:
      # By default it searches config named in spring.application.name property value
      name: common-config
      profile: ${spring.profiles.active}
  #When not using embedded ActiveMQ
  activemq:
    broker-url: tcp://localhost:61616


# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/