# HTTP Server
server:
  port: 8094

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
#Dev Docker profile
spring:
  profiles: dev_docker
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/